/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author guill
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        MainFrame frame1 = new MainFrame();
        frame1.setLocationRelativeTo(null);
        frame1.setVisible(true);
        initComponents();
    }

//    public int actualRAM() {
//        
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Company1 = new javax.swing.JPanel();
        HPLogo = new javax.swing.JLabel();
        Company2 = new javax.swing.JPanel();
        MSILogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        Background.setBackground(new java.awt.Color(0, 153, 204));
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.setPreferredSize(new java.awt.Dimension(1280, 720));

        Company1.setForeground(new java.awt.Color(0, 51, 51));
        Company1.setPreferredSize(new java.awt.Dimension(639, 720));

        HPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HP LOGO RESIZED.png"))); // NOI18N

        javax.swing.GroupLayout Company1Layout = new javax.swing.GroupLayout(Company1);
        Company1.setLayout(Company1Layout);
        Company1Layout.setHorizontalGroup(
            Company1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(HPLogo)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        Company1Layout.setVerticalGroup(
            Company1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(HPLogo)
                .addContainerGap(608, Short.MAX_VALUE))
        );

        Company2.setForeground(new java.awt.Color(51, 51, 0));
        Company2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Company2.setPreferredSize(new java.awt.Dimension(639, 720));

        MSILogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MSILogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MSI LOGO RESIZED.png"))); // NOI18N

        javax.swing.GroupLayout Company2Layout = new javax.swing.GroupLayout(Company2);
        Company2.setLayout(Company2Layout);
        Company2Layout.setHorizontalGroup(
            Company2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(MSILogo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        Company2Layout.setVerticalGroup(
            Company2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(MSILogo)
                .addContainerGap(598, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Company1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Company2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Company1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Company2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //Esto es lo que antes estaba en la clase Simulador
        //Para hacer que funcione como queremos, hay que cambiar el main
        System.out.println("Main cambiado");
        
        Warehouse almacen = new Warehouse(20, 55, 15, 35);  // Almacén con capacidad máxima de 20 CPUs, 55 RAMs, 15 placas base, y 35 fuentes de alimentación

        // Crear productores
        ProductorCPU productorCPU = new ProductorCPU(almacen, 72 * 1000, 26.0); // Produce cada 72 horas, salario por hora: 26.0
        ProductorRAM productorRAM = new ProductorRAM(almacen, 24 * 1000, 40.0); // Produce cada 24 horas, salario por hora: 40.0
        ProductorPlacaBase productorPlacaBase = new ProductorPlacaBase(almacen, 72 * 1000, 20.0); // Produce cada 72 horas, salario por hora: 20.0
        ProductorFuenteAlimentacion productorFuenteAlimentacion = new ProductorFuenteAlimentacion(almacen, (24 / 3) * 1000, 16.0); // Produce cada 8 horas (3 por día), salario por hora: 16.0

        // Crear ensambladores (HP y MSI)
        Ensamblador ensambladorHP = new Ensamblador(almacen, "HP");
        Ensamblador ensambladorMSI = new Ensamblador(almacen, "MSI");

        // Iniciar los hilos de los productores y ensambladores
        productorCPU.start();
        productorRAM.start();
        productorPlacaBase.start();
        productorFuenteAlimentacion.start();
        ensambladorHP.start();
        ensambladorMSI.start();

        MainFrame frame1 = new MainFrame();
        frame1.setLocationRelativeTo(null);
        frame1.setVisible(true);
        
        // Simular por un periodo de tiempo
        try {
            Thread.sleep(10000); // Simular por 10 segundos (ajustar según sea necesario)
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // Imprimir el salario total acumulado de los productores y ensambladores
        System.out.println("Salario total Productor CPU: " + productorCPU.getSalarioTotal());
        System.out.println("Salario total Productor RAM: " + productorRAM.getSalarioTotal());
        System.out.println("Salario total Productor Placa Base: " + productorPlacaBase.getSalarioTotal());
        System.out.println("Salario total Productor Fuente Alimentación: " + productorFuenteAlimentacion.getSalarioTotal());
        System.out.println("Salario total Ensamblador HP: " + ensambladorHP.getSalarioTotal());
        System.out.println("Salario total Ensamblador MSI: " + ensambladorMSI.getSalarioTotal());
        
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame2 = new MainFrame();
                frame2.setLocationRelativeTo(null);
                frame2.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Company1;
    private javax.swing.JPanel Company2;
    private javax.swing.JLabel HPLogo;
    private javax.swing.JLabel MSILogo;
    // End of variables declaration//GEN-END:variables
}
